const company_details = {
  company_data: {
    company_id: 496,
    status: "INCOMPLETE",
    company_abbreviations: "ZESA",
    company_name: "zesa holdings",
    company_start_date: "1985-01-01",
    company_short_description:
      "Zesa Holdings (Pvt) Ltd Is A Zimbabwean State-Owned Firm Tasked With Generating, Transmitting, And Distributing Energy. It Has Delegated This Task To Its Subsidiaries, Zimbabwe Power Company (Zpc) And Zimbabwe Electricity Transmission And Distribution Company (Zetdc). Other Subsidiaries Are Zesa Enterprises (Zent) Whose Mandate Is To Pursue Non-Regulated Business Activities That Add Value To The Zesa Group, Especially The Electricity Supply Chain. Powertel Communications (Pvt) Ltd Provides Information And Communication Technologies (Ict) Services To The Zesa Group And Sells Excess Capacity To Other External Customers",
    location: "Zimbabwe",
    website: "www.zesaholdings.co.zw",
    employees: 847,
  },
  company_logo: {
    company_logo: "Images_Doc/496_LOGO-ZESA-1.png",
  },
  business_category: {
    state_name: "Government Facility",
  },
  company_contact_details: {
    address_city: "New Ardbennie",
    address: "1 Harare Drive",
    state_code: 263,
    region: "Harare",
    country: "Zimbabwe",
    instagram: "zesaholdings",
    twitter: "zesaholdings",
    email: "",
    work_email: "pr@zedc.co.zw",
    phone1: 2427744919,
    phone2: 0,
    phone3: 0,
  },
  company_valuation: [
    {
      valuation_id: 1,
      valuation_date: "2025-01-01",
      valuation_method: "Book Value",
      valuation_amount: 180000000.0,
      valuation_currency: "USD",
      financial_year: 2025,
      financial_period: "Annual",
      current_growth_rate: 8.0,
      notes: "Value determined by Zesa Auditors",
    },
    {
      valuation_id: 2,
      valuation_date: "2025-01-01",
      valuation_method: "Book Value",
      valuation_amount: 150000000.0,
      valuation_currency: "USD",
      financial_year: 2024,
      financial_period: "Annual",
      current_growth_rate: -5.0,
      notes: "Value determined by Zesa Auditors",
    },
  ],
  company_documents: [
    {
      id: 232,
      document_name: "Zesa_Financials - December.pdf",
      company_doc: "Company_Documents/496_Zesa_Financials - December.pdf",
      created_at: null,
    },
    {
      id: 232,
      document_name: "Zesa_Financials - November.pdf",
      company_doc: "Company_Documents/496_Zesa_Financials - November.pdf",
      created_at: null,
    },
    {
      id: 232,
      document_name: "Zesa_Financials - October.pdf",
      company_doc: "Company_Documents/496_Zesa_Financials - October.pdf",
      created_at: null,
    },
  ],
  competition: {
    competition_name: "100 Startupper Challenge",
    status: "INCOMPLETE",
  },
  company_updates: [
    {
      update_id: 199,
      update_type: "News",
      headline: "Zetdc Commissions Alaska- Karoi Project",
      summary: "ZETDC commissions Alaska- Karoi project",
      update_content:
        "The project funded by the African Development Bank (AfDB), and constructed by Chinese firm, Sinohydro Corporation Limited, with the purpose of improving the power supply quality to Karoi and surrounding areas was in the first quarter of 2024 commissioned, connected and the substation energized to supply power to Karoi Town. The project which was approved in 2017, and commenced in 2021, is one of the many ZETDC network re-enforcement projects with an objective of strengthening and increasing the country’s sub-transmission network capacity. The scope of the project consisted of the construction of an 85km, 132 KV monopole line between Alaska 330/132kV substation and a new 132/33kV substation at Karoi, the construction of the new 132/33kV substation, and refurbishment of the reticulation network within the Makonde and Hurungwe districts. ",
      url: "https://www.zesaholdings.co.zw/2024/06/14/zetdc-commissions-alaska-karoi-project/",
      is_published: true,
    },
    {
      update_id: 200,
      update_type: "News",
      headline: "Ethopia In Zimbabwe",
      summary: "ETHIOPIA ELECTRICITY UTILITY TO TAKE A LEAF FROM ZETDC",
      update_content:
        "A delegation from the Ethiopia Electric Utility (EEU) visited ZETDC to benchmark on the Inhemeter prepayment metering project and the SmartVend system. The 5-day visit was made possible and facilitated by Inhemeter. EEU sought to learn from ZETDC on best practice on the replacement of conventional meters with prepaid meters hence the benchmark visit to ZETDC . Speaking in his opening remarks, ZETDC Acting Managing Director, Engineer Abel Gurupira highlighted the long term need for Africa to be one united continent, where countries can easily trade, collaborate, and exchange notes. Ethiopia has a total generation capacity of 43 173 GWh against an energy demand of 13 923 GWh meaning that the country has excess power for export which Southern Africa could utilize.  In his remarks, the Managing Director gave an account of ZETDC’s transition, from using Landis & Gyr, Suprima Vending system, to Itron Eclipse Enterprise Edition (3E) which later upgraded to IPMP. “At a certain point we discovered that we need to further improve the vending system to include elements like multi-currency and simultaneous transactions to cope with demands from the increasing customer base”, he said. The utility then upgraded to the Smart-vend system which has a capacity to accommodate a huge customer base as witnessed during benchmark visits which ZETDC did where Inhemeter implemented SmartVend ",
      url: "https://www.zesaholdings.co.zw/2024/06/14/ethiopia-electricy-utility-to-take-a-leaf-from-zetdc/",
      is_published: true,
    },
  ],
  company_directors: [
    {
      employee_id: 166,
      title: "Mr",
      first_name: "Fortune",
      last_name: "Chasi",
      dob: "1965-02-05T00:00:00",
      marital_status: "MARRIED",
      email: "",
      nationality: "Zimbabwean",
      employee_image: null,
    },
    {
      employee_id: 167,
      title: "Mr",
      first_name: "Sydney",
      last_name: "Gata",
      dob: "1955-09-05T00:00:00",
      marital_status: "MARRIED",
      email: "",
      nationality: "Zimbabwean",
      employee_image: null,
    },
  ],
  stock_market_details: {
    type_of_market: "N/A",
    listed_date: "N/A",
    listing_capital: null,
    listing_currency: null,
    delisted_date: null,
    current_market_cap: null,
    financial_year_end: null,
    transfer_secretary: null,
  },
  previous_funds: [
    {
      id: 232,
      investor_type: "Organization",
      investor_information: "Government Funded Institution",
      investment_type: "Grant",
      date_of_funds: "1985-01-04",
      investment_amount: 1500000.0,
      investment_currency: "USD",
      company_valuation: 18000000.0,
      company_valuation_currency: "USD",
      valuation_date: "2025-01-01",
    },
  ],
  company_review: {
    approver_status: "N/A",
    company_comment: "N/A",
    chip_type: "N/A",
    updated_by: "N/A",
  },
  company_request: {
    request_type: "Project Financing",
    request_status: "PENDING",
  },
  company_request_details: {
    total_required_cash: null,
    total_received_cash: null,
    remaining_cash: null,
  },
};
export default company_details;
